import type { ElementDefinition, PropDefinition } from '../elements/composer.js';
import type { ActionDefinition, ValidatorDefinition, ExpressionHandlerDefinition } from '../types.js';
import type { DesignTokens } from '../design/tokens.js';

export interface ReferenceDocConfig {
  /** Project name */
  name: string;
  /** Available primitives (type names) */
  primitives: string[];
  /** Custom element definitions (Layer 3) */
  elements?: ElementDefinition[];
  /** Design tokens */
  tokens?: DesignTokens;
  /** Registered actions */
  actions?: ActionDefinition[];
  /** Registered validators */
  validators?: ValidatorDefinition[];
  /** Extra expression handlers (beyond built-in) */
  extraExpressions?: ExpressionHandlerDefinition[];
}

/**
 * Generate a complete reference document (markdown) for AI consumption.
 * This is the primary product of Mythik — what makes the AI effective.
 */
export function generateReferenceDoc(config: ReferenceDocConfig): string {
  const sections: string[] = [];

  sections.push(generateHeader(config.name));
  sections.push(generateExpressionReference());
  sections.push(generatePrimitivesReference(config.primitives));

  if (config.elements && config.elements.length > 0) {
    sections.push(generateElementsReference(config.elements));
  }

  if (config.tokens) {
    sections.push(generateTokensReference(config.tokens));
  }

  sections.push(generateActionsReference(config.actions));
  sections.push(generateTransactionReference());
  sections.push(generateValidatorsReference(config.validators));
  sections.push(generateDeriveReference());
  sections.push(generateDataSourcesReference());
  sections.push(generateTemplatesReference());
  sections.push(generateRepeatEnhancedReference());
  sections.push(generateSpecStructure());
  sections.push(generateRules());
  sections.push(generatePatchReference());

  return sections.join('\n\n---\n\n');
}

function generateHeader(name: string): string {
  return `# ${name} — Mythik Reference Document

> This document is auto-generated by Mythik. The AI reads this to produce correct JSON configs.
> Do NOT edit manually — changes will be overwritten on regeneration.

## How to Use This Document

When asked to create or modify UI, produce a JSON **Spec** following the structure and rules below.
Every element type, expression, action, and validator available is documented here with examples.`;
}

function generateExpressionReference(): string {
  return `## Expression Types

Expressions are special JSON objects that resolve to dynamic values at runtime.

### \`$state\` — Read from state
\`\`\`json
{ "$state": "/user/name" }
\`\`\`
Reads the value at the given JSON Pointer path from application state.

### \`$bindState\` — Two-way binding
\`\`\`json
{ "$bindState": "/form/email" }
\`\`\`
Reads AND writes. When the user changes the input, the state updates automatically.

### \`$token\` — Design system token
\`\`\`json
{ "$token": "colors.primary" }
{ "$token": "spacing.unit", "multiply": 3 }
\`\`\`
Resolves a value from the design system. Use dot notation. \`multiply\` scales numeric tokens.

### \`$cond\` / \`$then\` / \`$else\` — Conditional value
\`\`\`json
{
  "$cond": { "$state": "/form/isValid" },
  "$then": { "$token": "colors.success" },
  "$else": { "$token": "colors.muted" }
}
\`\`\`
Evaluates a condition. Supports operators: \`eq\`, \`neq\`, \`gt\`, \`gte\`, \`lt\`, \`lte\`, \`not\`.

### \`$switch\` — Multi-Branch Conditional
\`\`\`json
{ "$switch": { "$state": "/filter/type" }, "cases": { "1": "Active", "2": "Inactive" }, "default": "Other" }
\`\`\`
Evaluates value, matches against case keys (strict equality). Returns matched case or default.

### \`$template\` — String interpolation
\`\`\`json
{ "$template": "Hello, \${/user/name}! You have \${/inbox/count} messages." }
\`\`\`
Interpolates values into a string. Supports two reference types:
- State paths: \`\${/user/name}\` — reads from application state
- \`$let\` bindings: \`\${age}\` — reads from a named binding defined with \`$let\`

Example combining both:
\`\`\`json
{
  "$let": { "age": { "$computed": "calculateAge", "args": { "birthDate": { "$state": "/patient/birthDate" } } } },
  "$in": { "$template": "Patient: \${/patient/name} — \${age} years old" }
}
\`\`\`

### \`$computed\` — Registered function
\`\`\`json
{ "$computed": "calculateBMI", "args": { "weight": { "$state": "/patient/weight" }, "height": { "$state": "/patient/height" } } }
\`\`\`
Calls a registered function with resolved arguments.

### \`$let\` / \`$ref\` — Named bindings
\`\`\`json
{
  "$let": { "bmi": { "$computed": "calculateBMI", "args": { ... } } },
  "$in": { "$ref": "bmi" }
}
\`\`\`
Define a named value once, reference it multiple times. Avoids repetition.

### \`$i18n\` — Translation
\`\`\`json
{ "$i18n": "patient.name" }
{ "$i18n": "welcome", "args": { "name": { "$state": "/user/name" } } }
\`\`\`
Resolves a translation key for the active locale. Supports argument interpolation.

### \`$breakpoint\` — Responsive value
\`\`\`json
{ "$breakpoint": { "sm": 1, "md": 2, "lg": 3 } }
\`\`\`
Resolves to different values based on viewport width.

### \`$item\` / \`$index\` — Repeat context (read-only)
\`\`\`json
{ "$item": "title" }
{ "$item": "" }
{ "$index": true }
\`\`\`
Inside a \`repeat\` block: \`$item\` reads a field from the current item, \`$index\` returns the position.

### \`$group\` — Group Context (inside repeat.groupBy)
\`\`\`json
{ "$group": "key" }     → group key value
{ "$group": "items" }   → array of items in group
{ "$group": "index" }   → group index (0-based)
{ "$group": "count" }   → number of items in group (sugar for items.length)
\`\`\`
Only valid inside repeat with groupBy. Used in groupHeader/groupFooter elements.

### \`$selection\` — Selection State (inside repeat.selection)
\`\`\`json
{ "$selection": "selected" }  → true if current item is selected
{ "$selection": "count" }     → number of selected items
\`\`\`
Only valid inside repeat with selection config. Sugar for $array includes/count.

### \`$bindItem\` — Repeat context (two-way)
\`\`\`json
{ "$bindItem": "completed" }
\`\`\`
Two-way binding to a field in the current repeat item.

### \`$prop\` — Element prop reference (Layer 3)
\`\`\`json
{ "$prop": "label" }
\`\`\`
References a prop passed to a custom element definition. Used inside element render trees.

### \`$math\` — Arithmetic operations
\`\`\`json
{ "$math": "add", "args": [{ "$state": "/a" }, { "$state": "/b" }] }
{ "$math": "multiply", "args": [{ "$state": "/price" }, { "$state": "/qty" }] }
{ "$math": "round", "value": 3.14159, "decimals": 2 }
\`\`\`
Operations: \`add\`, \`subtract\`, \`multiply\`, \`divide\`, \`round\`, \`floor\`, \`ceil\`, \`abs\`, \`min\`, \`max\`, \`mod\`

### \`$array\` — Array operations
\`\`\`json
{ "$array": "count", "source": { "$state": "/products" } }
{ "$array": "count", "source": { "$state": "/products" }, "where": { "field": "stock", "lt": 10 } }
{ "$array": "sum", "source": { "$state": "/products" }, "field": "price" }
{ "$array": "sumProduct", "source": { "$state": "/products" }, "field1": "price", "field2": "stock" }
{ "$array": "filter", "source": { "$state": "/items" }, "where": { "field": "status", "eq": "active" } }
{ "$array": "remove", "source": { "$state": "/items" }, "where": { "field": "id", "eq": 3 } }
{ "$array": "append", "source": { "$state": "/items" }, "value": { "name": "New Item" } }
{ "$array": "replace", "source": { "$state": "/items" }, "where": { "field": "id", "eq": 1 }, "value": { "name": "Updated" } }
{ "$array": "toggle", "source": { "$state": "/selectedIds" }, "value": 5 }
{ "$array": "search", "source": { "$state": "/products" }, "query": { "$state": "/search" }, "fields": ["name", "category"] }
{ "$array": "slice", "source": { "$state": "/items" }, "from": 0, "to": 10 }
{ "$array": "sort", "source": { "$state": "/items" }, "field": "name", "direction": "asc" }
{ "$array": "find", "source": { "$state": "/items" }, "where": { "field": "id", "eq": 1 } }
{ "$array": "includes", "source": { "$state": "/tags" }, "value": "urgent" }
{ "$array": "map", "source": { "$state": "/items" }, "field": "name" }
{ "$array": "first", "source": { "$state": "/items" } }
{ "$array": "last", "source": { "$state": "/items" } }
\`\`\`
Where operators: \`eq\`, \`neq\`, \`gt\`, \`gte\`, \`lt\`, \`lte\`, \`in\`, \`notIn\`

### \`$date\` — Date operations
\`\`\`json
{ "$date": "now" }
{ "$date": "today" }
{ "$date": "age", "from": { "$state": "/birthDate" } }
{ "$date": "diff", "from": { "$state": "/start" }, "to": { "$state": "/end" }, "unit": "days" }
{ "$date": "format", "value": { "$state": "/date" }, "pattern": "short" }
{ "$date": "add", "value": { "$state": "/date" }, "amount": 7, "unit": "days" }
\`\`\`
Units: \`days\`, \`months\`, \`years\`, \`hours\`, \`minutes\`. Patterns: \`short\`, \`long\`, \`numeric\`, \`time\`, \`datetime\`

### \`$format\` — Value formatting
\`\`\`json
{ "$format": "currency", "value": { "$state": "/price" }, "currency": "USD" }
{ "$format": "number", "value": 1234.5, "decimals": 2 }
{ "$format": "percent", "value": 0.75 }
{ "$format": "phone", "value": { "$state": "/phone" } }
{ "$format": "uppercase", "value": { "$state": "/name" } }
{ "$format": "lowercase", "value": "HELLO" }
{ "$format": "capitalize", "value": "hello world" }
{ "$format": "truncate", "value": "long text...", "length": 20 }
\`\`\`
Extended options: locale, notation ("compact", "scientific"), signDisplay ("auto", "always"), useGrouping (boolean).

### \`$and\` / \`$or\` / \`$not\` — Boolean logic
\`\`\`json
{ "$and": [{ "$state": "/form/name" }, { "$state": "/form/price" }] }
{ "$or": [{ "$state": "/user/isAdmin" }, { "$state": "/user/isModerator" }] }
{ "$not": { "$state": "/form/isValid" } }
\`\`\`
Works everywhere — \`visible\`, \`disabled\`, \`style\`, any prop. Returns true/false.`;
}

function generatePrimitivesReference(primitives: string[]): string {
  const lines = primitives.map((p) => `- \`${p}\``);
  return `## Available Primitives

These are the built-in visual building blocks. Use them as the \`type\` field in elements.

${lines.join('\n')}

Each primitive accepts \`style\` (CSS object), \`visible\` (condition), and \`permission\` (role-based access).

**Theme auto-inheritance:** All interactive primitives (input, textarea, select, checkbox, toggle, slider, button, accordion, tabs) automatically inherit colors from the design system tokens. No \`$token\` references needed for basic theming — it works in both light and dark mode by default. Use explicit \`style\` props only when you need per-field overrides.

**Input format prop:** The \`input\` primitive supports a \`format\` prop for display masking:
- \`"phone"\` — displays as (555) 123-4567, stores raw digits
- \`"currency"\` — displays as $1,234.56, stores raw number

Example: \`{ "type": "input", "props": { "label": "Phone", "value": { "$bindState": "/phone" }, "format": "phone" } }\``;
}

function generateElementsReference(elements: ElementDefinition[]): string {
  const elementDocs = elements.map((el) => {
    const propsDoc = Object.entries(el.props).map(([name, def]) => {
      const parts = [`  - \`${name}\`: ${def.type}`];
      if (def.default !== undefined) parts.push(`(default: ${JSON.stringify(def.default)})`);
      if (def.values) parts.push(`(options: ${def.values.join(', ')})`);
      if (def.bindable) parts.push(`(bindable)`);
      return parts.join(' ');
    });

    return `### \`${el.type}\`

**Props:**
${propsDoc.join('\n')}

**Usage:**
\`\`\`json
{
  "type": "${el.type}",
  "props": { ${Object.entries(el.props).map(([n, d]) => `"${n}": ${JSON.stringify(d.default ?? `<${d.type}>`)}`).join(', ')} }
}
\`\`\``;
  });

  return `## Custom Elements (Layer 3)

These are reusable components composed from primitives. Use them like primitives.

${elementDocs.join('\n\n')}`;
}

function generateTokensReference(tokens: DesignTokens): string {
  const tokenLines: string[] = [];

  function walkTokens(obj: Record<string, unknown>, prefix: string) {
    for (const [key, value] of Object.entries(obj)) {
      if (key === 'modes') continue;
      const path = prefix ? `${prefix}.${key}` : key;
      if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
        walkTokens(value as Record<string, unknown>, path);
      } else {
        tokenLines.push(`| \`${path}\` | \`${JSON.stringify(value)}\` |`);
      }
    }
  }

  walkTokens(tokens as unknown as Record<string, unknown>, '');

  const modesDoc = tokens.modes
    ? `\n\n**Available modes:** ${Object.keys(tokens.modes).join(', ')}`
    : '';

  return `## Design System Tokens

Reference tokens with \`{ "$token": "path" }\`. Available tokens:

| Path | Value |
|------|-------|
${tokenLines.join('\n')}${modesDoc}`;
}

function generateActionsReference(actions?: ActionDefinition[]): string {
  const builtinActions = [
    '| `setState` | `{ statePath, value }` | Set a value in state |',
    '| `navigate` | `{ screen, ...params }` | Navigate to a screen |',
    '| `goBack` | — | Go to previous screen |',
    '| `openModal` | `{ id }` | Show a modal |',
    '| `closeModal` | `{ id }` | Hide a modal |',
    '| `openDrawer` | `{ id }` | Open a drawer |',
    '| `closeDrawer` | `{ id }` | Close a drawer |',
    '| `showNotification` | `{ message, type }` | Show a toast/snackbar |',
    '| `toggleTheme` | — | Switch dark/light mode |',
    '| `setLocale` | `{ locale }` | Change language |',
    '| `copyToClipboard` | `{ value }` | Copy to clipboard |',
    '| `openUrl` | `{ url }` | Open external URL |',
    '| `fetch` | `{ url, method, body, target, headers }` | HTTP request, writes response to target state path |',
    '| `submitForm` | `{ url, method, body, target, successMessage }` | Validate + HTTP request + success notification |',
  ];

  const customLines = (actions ?? []).map(
    (a) => `| \`${a.name}\` | custom | Custom action |`,
  );

  return `## Actions

Wire actions to events with the \`on\` property:

\`\`\`json
{
  "on": {
    "press": { "action": "navigate", "params": { "screen": "detail", "id": { "$state": "/selected/id" } } }
  }
}
\`\`\`

Multiple actions:
\`\`\`json
{
  "on": {
    "press": [
      { "action": "setState", "params": { "statePath": "/loading", "value": true } },
      { "action": "navigate", "params": { "screen": "next" } }
    ]
  }
}
\`\`\`

| Action | Params | Purpose |
|--------|--------|---------|
${[...builtinActions, ...customLines].join('\n')}`;
}

function generateTransactionReference(): string {
  return `## Transactions (Optimistic Updates)

Use \`transaction\` for CRUD operations that need instant UI feedback. The framework takes a state snapshot, applies your changes instantly, then confirms with the server. On failure, it rolls back automatically.

### Structure

\`\`\`json
{
  "on": {
    "press": {
      "transaction": {
        "before": [/* UI transitions — NOT rolled back */],
        "optimistic": [/* Data changes — ROLLED BACK on error */],
        "confirm": [/* Network request — determines success/failure */],
        "onSuccess": [/* Post-success sync (optional) */],
        "onError": [/* User notification (optional, runs after rollback) */]
      }
    }
  }
}
\`\`\`

### Decision Rule

- **"Would I undo this if the server says no?"** → \`optimistic\`
- **"Should this happen regardless?"** → \`before\`

| Action | Phase | Why |
|--------|-------|-----|
| \`closeModal\` | \`before\` | Don't reopen on error |
| \`setState\` (data) | \`optimistic\` | Rollback if server rejects |
| \`setState\` (form reset) | \`optimistic\` | Restore form so user can retry |
| \`navigate\` | \`before\` | Stay on page, show error there |

### Confirm result access

The \`fetch\` in \`confirm\` can write to \`/tx/result\` via \`target\`. \`onSuccess\` reads it with \`{ "$state": "/tx/result" }\`. On error, \`/tx/error\` contains \`{ message }\`. Both are cleaned up automatically after the transaction.

### Timeout

Default: 10 seconds. Override with \`timeout\` (ms):

\`\`\`json
{ "transaction": { "timeout": 30000, "confirm": [...] } }
\`\`\`

---

## Transaction Templates

Copy the template for your operation, replace the \`{{PLACEHOLDERS}}\`.

### CREATE — Add item to list

\`\`\`json
{
  "transaction": {
    "before": [
      { "action": "closeModal", "params": { "id": "{{MODAL_ID}}" } }
    ],
    "optimistic": [
      { "action": "setState", "params": {
        "statePath": "{{ARRAY_PATH}}",
        "value": { "$array": "append", "source": { "$state": "{{ARRAY_PATH}}" }, "value": {
          "id": { "$template": "temp-\${/form/title}" },
          "{{FIELD_1}}": { "$state": "/form/{{FIELD_1}}" },
          "{{FIELD_2}}": { "$state": "/form/{{FIELD_2}}" }
        }}
      }}
    ],
    "confirm": [
      { "action": "fetch", "params": {
        "method": "POST",
        "url": "{{API_URL}}",
        "headers": { "Prefer": "return=representation" },
        "body": {
          "{{FIELD_1}}": { "$state": "/form/{{FIELD_1}}" },
          "{{FIELD_2}}": { "$state": "/form/{{FIELD_2}}" }
        },
        "target": "/tx/result"
      }}
    ],
    "onSuccess": [
      { "action": "fetch", "params": {
        "method": "GET",
        "url": "{{API_URL}}?select=*&order=created_at.desc",
        "target": "{{ARRAY_PATH}}"
      }}
    ],
    "onError": [
      { "action": "showNotification", "params": { "type": "error", "message": "Could not create {{ENTITY}}. Please try again." } }
    ]
  }
}
\`\`\`

### UPDATE — Edit item in list

\`\`\`json
{
  "transaction": {
    "before": [
      { "action": "closeModal", "params": { "id": "{{MODAL_ID}}" } }
    ],
    "optimistic": [
      { "action": "setState", "params": {
        "statePath": "{{ARRAY_PATH}}",
        "value": { "$array": "replace", "source": { "$state": "{{ARRAY_PATH}}" },
          "where": { "field": "id", "eq": { "$state": "/form/editId" } },
          "value": {
            "id": { "$state": "/form/editId" },
            "{{FIELD_1}}": { "$state": "/form/{{FIELD_1}}" },
            "{{FIELD_2}}": { "$state": "/form/{{FIELD_2}}" }
          }
        }
      }}
    ],
    "confirm": [
      { "action": "fetch", "params": {
        "method": "PATCH",
        "url": { "$template": "{{API_URL}}?id=eq.\${/form/editId}" },
        "headers": { "Prefer": "return=representation" },
        "body": {
          "{{FIELD_1}}": { "$state": "/form/{{FIELD_1}}" },
          "{{FIELD_2}}": { "$state": "/form/{{FIELD_2}}" }
        },
        "target": "/tx/result"
      }}
    ],
    "onSuccess": [
      { "action": "fetch", "params": {
        "method": "GET",
        "url": "{{API_URL}}?select=*&order=created_at.desc",
        "target": "{{ARRAY_PATH}}"
      }}
    ],
    "onError": [
      { "action": "showNotification", "params": { "type": "error", "message": "Could not update {{ENTITY}}. Please try again." } }
    ]
  }
}
\`\`\`

### DELETE — Remove item from list

\`\`\`json
{
  "transaction": {
    "before": [
      { "action": "closeModal", "params": { "id": "{{CONFIRM_MODAL_ID}}" } }
    ],
    "optimistic": [
      { "action": "setState", "params": {
        "statePath": "{{ARRAY_PATH}}",
        "value": { "$array": "remove", "source": { "$state": "{{ARRAY_PATH}}" },
          "where": { "field": "id", "eq": { "$state": "/ui/deleteId" } }
        }
      }}
    ],
    "confirm": [
      { "action": "fetch", "params": {
        "method": "DELETE",
        "url": { "$template": "{{API_URL}}?id=eq.\${/ui/deleteId}" }
      }}
    ],
    "onError": [
      { "action": "showNotification", "params": { "type": "error", "message": "Could not delete {{ENTITY}}. Please try again." } }
    ]
  }
}
\`\`\`

### TOGGLE — Flip a boolean value

\`\`\`json
{
  "transaction": {
    "optimistic": [
      { "action": "setState", "params": {
        "statePath": "{{BOOLEAN_PATH}}",
        "value": { "$not": { "$state": "{{BOOLEAN_PATH}}" } }
      }}
    ],
    "confirm": [
      { "action": "fetch", "params": {
        "method": "PATCH",
        "url": { "$template": "{{API_URL}}?id=eq.{{ITEM_ID}}" },
        "body": { "{{FIELD}}": { "$state": "{{BOOLEAN_PATH}}" } }
      }}
    ],
    "onError": [
      { "action": "showNotification", "params": { "type": "error", "message": "Could not update. Please try again." } }
    ]
  }
}
\`\`\``;
}

function generateValidatorsReference(validators?: ValidatorDefinition[]): string {
  const builtinValidators = [
    '| `required` | — | Non-empty value |',
    '| `email` | — | Valid email format |',
    '| `minLength` | `{ min }` | Minimum string length |',
    '| `maxLength` | `{ max }` | Maximum string length |',
    '| `pattern` | `{ pattern }` | Regex match |',
    '| `min` | `{ min }` | Minimum number |',
    '| `max` | `{ max }` | Maximum number |',
    '| `numeric` | — | Must be a number |',
    '| `url` | — | Valid URL |',
    '| `matches` | `{ other }` | Must equal another field |',
    '| `equalTo` | `{ other }` | Must equal another field |',
    '| `greaterThan` | `{ other }` | Must be greater than another field |',
    '| `lessThan` | `{ other }` | Must be less than another field |',
    '| `requiredIf` | `{ field }` | Required when condition field is truthy |',
  ];

  const customLines = (validators ?? []).map(
    (v) => `| \`${v.name}\` | custom | ${v.message ?? 'Custom validator'} |`,
  );

  return `## Validation

Add validation to input fields:

\`\`\`json
{
  "type": "input",
  "props": {
    "value": { "$bindState": "/form/email" },
    "checks": [
      { "type": "required", "message": "Email is required" },
      { "type": "email", "message": "Invalid email format" }
    ],
    "validateOn": "blur"
  }
}
\`\`\`

| Validator | Args | Purpose |
|-----------|------|---------|
${[...builtinValidators, ...customLines].join('\n')}`;
}

function generateSpecStructure(): string {
  return `## Spec Structure (Flat Tree)

Every screen is a JSON Spec with a \`root\` ID and a flat \`elements\` map:

\`\`\`json
{
  "screen": "patient-detail",
  "root": "main-layout",
  "state": { "patient": {}, "activeTab": "general" },
  "elements": {
    "main-layout": {
      "type": "stack",
      "props": { "direction": "vertical" },
      "children": ["header", "content"]
    },
    "header": {
      "type": "text",
      "props": { "content": { "$template": "\${/patient/name}" }, "variant": "heading" }
    },
    "content": {
      "type": "box",
      "props": { "style": { "padding": { "$token": "spacing.unit", "multiply": 3 } } },
      "children": ["field1", "field2"]
    }
  }
}
\`\`\`

### Element Properties

| Property | Type | Purpose |
|----------|------|---------|
| \`type\` | string | Primitive or element name |
| \`props\` | object | Component props (can contain expressions) |
| \`children\` | string[] | IDs of child elements |
| \`style\` | object | CSS styles (can contain expressions) |
| \`visible\` | boolean or condition | Show/hide condition |
| \`permission\` | object | Role-based access: \`{ visible, editable, readonly }\` |
| \`repeat\` | object | Iterate over array: \`{ statePath, key }\` or \`{ source: expression, key }\` |
| \`watch\` | object | React to state changes: \`{ "/path": [actions] }\` |
| \`on\` | object | Event handlers: \`{ press: action, change: action }\` |

### Visibility Conditions

\`\`\`json
{ "$state": "/user/role", "eq": "admin" }
[{ "$state": "/form/isValid" }, { "$state": "/form/hasChanges" }]
{ "$or": [{ "$state": "/user/isVIP" }, { "$state": "/cart/total", "gt": 200 }] }
{ "$and": [{ "$state": "/user/active" }, { "$state": "/user/verified" }] }
\`\`\``;
}

function generateRules(): string {
  return `## Rules

1. **Always use the flat tree structure** — root + elements map with string IDs for children
2. **Use \`$token\` for all visual values** — never hardcode colors, spacing, fonts, etc.
3. **Use \`$i18n\` for all user-facing text** — never hardcode strings
4. **Use \`$bindState\` for form inputs** — enables two-way data binding
5. **Use \`$cond\` for dynamic styles** — conditional colors, sizes, visibility
6. **Use \`$template\` for computed strings** — interpolation over concatenation
7. **Use \`$math\`, \`$array\`, \`$date\`, \`$format\` instead of \`$computed\`** — built-in operations cover 90%+ of cases without code
8. **Use \`$and\`/\`$or\`/\`$not\` for boolean logic in any prop** — works in \`disabled\`, \`style\`, \`visible\`, anywhere
9. **Use \`$array: 'search'\` for filtering lists** — case-insensitive multi-field search from config
10. **Use \`repeat.source\` with expressions for paginated/filtered lists** — chain \`$array: 'search'\` → \`$array: 'slice'\`
11. **Prefer visibility over disabled for conditional buttons** — simpler and cleaner
12. **Use \`required: true\` and \`checks\` for form validation** — validates on blur with error messages
13. **Field IDs must be unique within the spec** — use descriptive names: \`patient-name\`, \`submit-btn\`
14. **Arrays for ordered collections** — never objects
15. **Each element should have a clear purpose** — one element = one visual unit
16. **Validate user inputs** — add \`checks\` to every input field
17. **Use \`$switch\` for 3+ conditional branches** — instead of nested \`$cond\`
18. **Use \`dataSources\` for reactive data fetching** — specs should be self-contained
19. **Use \`templates\` for repeated element patterns** — reduces spec size
20. **Use \`repeat.groupBy\` for grouped data** — instead of pre-processing in the API
21. **Headers come from state (\`initialState\`)** — NEVER hardcode API keys in specs
22. **Use \`table\` primitive with sorting/pagination/groupBy flags** — for data tables`;
}

function generateDeriveReference(): string {
  return `## Derive — Auto-Computed State

\`\`\`json
{
  "derive": {
    "/derived/total": { "$math": [{ "$state": "/subtotal" }, "+", { "$state": "/tax" }] },
    "/derived/pct": { "$math": [{ "$state": "/completed" }, "/", { "$state": "/total" }] }
  }
}
\`\`\`

Derived paths are auto-computed when dependencies change. Topological sort ensures correct evaluation order. Derived paths are read-only (setState to them throws).`;
}

function generateDataSourcesReference(): string {
  return `## DataSources — Declarative Data Fetching

\`\`\`json
{
  "dataSources": {
    "tasks": {
      "url": { "$template": "\${/config/apiUrl}/api/tasks" },
      "params": { "page": { "$state": "/pagination/page" }, "search": { "$state": "/filter/search" } },
      "target": "/tasks",
      "trigger": "auto",
      "debounce": 300,
      "headers": { "$state": "/config/headers" }
    }
  }
}
\`\`\`

| Property | Type | Default | Description |
|----------|------|---------|-------------|
| url | Expression | required | Request URL |
| method | string | "GET" | HTTP method |
| headers | Expression | — | Request headers (from state, NOT hardcoded) |
| params | Record<string, Expression> | — | Reactive params. Null/""/all values omitted |
| target | string | required | State path for response data |
| trigger | "auto" \\| "manual" | "auto" | auto: re-fetch on param change |
| debounce | number | 0 | Debounce ms for auto-trigger |
| initialFetch | boolean | true | Fetch on mount |
| emptyWhileLoading | boolean | false | Clear target during loading |

Auto-generated state paths: \`{target}Loading\` (boolean), \`{target}Error\` (object|null).

Action: \`{ "action": "refreshDataSource", "params": { "id": "tasks" } }\` — forces re-fetch.`;
}

function generateTemplatesReference(): string {
  return `## Templates — Reusable Element Definitions

\`\`\`json
{
  "templates": {
    "monetary-col": {
      "type": "text",
      "defaults": { "color": "#0F172A" },
      "props": { "content": { "$prop": "value" } },
      "style": { "textAlign": "right", "color": { "$prop": "color" } }
    }
  },
  "elements": {
    "col-votado": { "type": "monetary-col", "props": { "value": "1,000.00" } },
    "col-mod": { "type": "monetary-col", "props": { "value": "500.00", "color": "#D97706" } }
  }
}
\`\`\`

Templates define reusable element shapes with $prop parameterization. Element props override template defaults. Use "$children" in template children to inject the consuming element's children.`;
}

function generateRepeatEnhancedReference(): string {
  return `## Repeat Enhanced

### groupBy — Client-Side Grouping
\`\`\`json
"repeat": { "source": { "$state": "/data" }, "groupBy": "category", "groupHeader": ["cat-header"], "groupFooter": ["cat-footer"], "footer": ["grand-total"] }
\`\`\`

### groupBy — Pre-Grouped Data
\`\`\`json
"repeat": { "source": { "$state": "/groups" }, "groupKey": "name", "groupItems": "rows", "groupHeader": ["header"] }
\`\`\`

### selection — Multi-Select in Repeat
\`\`\`json
"repeat": { "source": { "$state": "/items" }, "key": "id", "selection": { "state": "/selectedIds", "key": "id", "mode": "multiple" } }
\`\`\`
Enables $selection expressions inside the repeat. Use toggleSelection/selectAll/selectNone actions.`;
}

function generatePatchReference(): string {
  return `## Spec Modification via Patches

When modifying an existing spec, use RFC 6902 JSON Patch operations instead of rewriting the entire spec.

### Workflow

1. **Read the manifest** — see the element tree structure (which elements exist, their types, parent-child relationships)
2. **Request element details** — get the full definition of specific elements you need to understand or modify
3. **Generate patches** — produce an array of RFC 6902 operations targeting specific paths

### Patch Operations

**Add a new element:**
\`\`\`json
[
  { "op": "add", "path": "/elements/export-btn", "value": { "type": "button", "props": { "label": "Export" } } },
  { "op": "add", "path": "/elements/header/children/-", "value": "export-btn" }
]
\`\`\`

**Modify an existing prop:**
\`\`\`json
[
  { "op": "replace", "path": "/elements/title/props/content", "value": "New Title" }
]
\`\`\`

**Remove an element:**
\`\`\`json
[
  { "op": "remove", "path": "/elements/header/children/2" },
  { "op": "remove", "path": "/elements/old-widget" }
]
\`\`\`

**Move an element to a different parent:**
\`\`\`json
[
  { "op": "remove", "path": "/elements/header/children/1" },
  { "op": "add", "path": "/elements/footer/children/-", "value": "search-input" }
]
\`\`\`

**Add an initialAction:**
\`\`\`json
[
  { "op": "add", "path": "/initialActions/-", "value": { "action": "fetch", "params": { "url": "...", "target": "/data" } } }
]
\`\`\`

### Patch Rules

1. **Maintain children ↔ elements consistency** — adding an element to \`/elements/{id}\` requires also adding its ID to a parent's \`children\` array
2. **Remove from both places** — removing an element means removing from parent's \`children\` AND from \`/elements/{id}\`
3. **Use \`/-\` to append** — adds to the end of an array (children, initialActions)
4. **Use index paths for position** — \`/children/2\` targets the third child for removal or insertion
5. **Prefer \`replace\` over \`remove\` + \`add\`** — simpler and atomic for value changes
6. **Include complete element definitions** — when adding elements, include all props, events, children, and visibility conditions`;
}
